version: '3'

services:
  puzzle-game:
    build: .
    image: puzzle-game:latest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./stats:/app/stats
      - ./assets:/app/assets
    network_mode: "host"